data/compatibility/compat-DEV.xml
C64/Apple version of the game has been completable for some time now (3 years)
=> Remove comment about C64/Apple ManiacMansion

data/news/de/20151111.xml, data/news/de/20160119.xml
This pull request adds the German translation of the announcement about the upcoming server move to easyname.at.
It also fixes a missing space in the German announcement of the support for BBVS.
=> WEB: Translate announcement of server movement to German

lang/lang.de.ini
This PR adds a German translation to the downloads.xml
that was recently partially merged into lang.ini.
=> WEB: Add German translation of the Downloads page

data/news/de/20160304.xml
This adds the German translation of the 1.8.0 release news. Sorry for the delay.
=> WEB/DE: Translate 1.8.0 release news

lang/lang.de.ini
Translate the donation paragraph to German.
=> WEB: Translate donation paragraph to german

data/game_demos.xml
=> WEB: Remove requirement notice for MM64 Demo

lang/lang.de.ini
- Cleanup
- Consistency
- Typos
- some stuff we can fight over :-)
=> WEB: German translation cleanup

data/menus.de.xml, data/menus.fr.xml, data/menus.it.xml, data/menus.ru.xml, data/menus.xml
Maybe creating a link to the translation website might help to gain even more contributors.
=> WEB: Add a link to the translation website to the side menu

data/compatibility/compat-DEV.xml
Added to ScummVM by commit e4ab357 on May 2.
=> Adding Plumbers Don't Wear Ties to the compatibility list

lang/lang.de.ini, lang/lang.fr.ini, lang/lang.ini, lang/lang.it.ini, lang/lang.ru.ini
Very minor, but the games in the header didn't reflect the newly supported SCI32 games.
=> Update SCI games to reflect 2.0 support

include/config.inc.php
v2.0.0 is already in buster and sid
=> WEB: Update debian package version

data/credits.xml
I hope I did this right. I ran `devtools/credits.pl --xml` from updated main repo.
=> WEB: Sync credits

data/documentation.xml, data/downloads.xml, data/faq-xml.xml, data/faq-xml.xsl, data/games.xml, data/links.xml, data/menus.xml, data/press_articles.xml, data/screenshots.xml, data/subprojects.xml
The compatibility files have already been changed through #113. Changing the rest for consistency. Compared the pages and didn't see any differences.
=> DATA: Changing all XML files to UTF-8

README.md
It seems there were a few steps missing since the data structure change. I updated the readme to include them.
=> WEB: Adding missing data on how to set up the site since data structure change

.browserslistrc, build.js, composer.json, composer.lock, include/DataUtils.php, package.json
This PR moves away from php scss compiler to the official Dart compiler.
It also improves the site update process by updating the data files in parallel.
=> BUILD: Build improvements

include/OrmObjects/Compatibility.php
=> Fixing unsupported platforms not appearing

composer.lock, package-lock.json
Looks like these haven't been updated in a long time. I updated them this morning and this is what I got.
=> WEB: Updating composer.lock and package-lock.json

include/OrmObjects/Compatibility.php, include/Pages/StaticPage.php
Ran `composer lint` and accepted its auto-fixes
=> WEB: Fixing lint errors

include/Models/DownloadsModel.php
=> WEB: Sort downloads by version

include/Constants.php, include/Objects/File.php
I suspect this will fix an issue with the hashes and such showing up locally, but not on the server.
=> WEB: Use absolute file path if available

include/FileUtils.php, include/Models/DownloadsModel.php, include/Objects/File.php
More functionality that existed in code, but it didn't work.
Also includes refactoring of the File class.
=> WEB: Adding file size and extension to recommended downloads

data/en/scummvm_downloads.yaml, include/Models/DownloadsModel.php, include/Objects/File.php, include/Objects/WebLink.php, schema.xml, templates/components/list_items.tpl, templates/components/recommended_download.tpl, templates/pages/links.tpl
This involved renaming the spreadsheet column from "Description" to "Notes"
=> DATA: Restoring extra info on downloads page

data/en/links.yaml
These mods are made possible by ScummVM.
=> DATA: Adding links to other ScummVM game mods

data/en/news/20220216.markdown
using these screenshots
https://www.scummvm.org/data/screenshots/trilobyte/11h/11h_win_en_1_1_full.png
https://www.scummvm.org/data/screenshots/trilobyte/11h/11h_win_en_1_6_full.png
https://www.scummvm.org/data/screenshots/trilobyte/clandestiny/clandestiny_win_en_1_1_full.png
https://www.scummvm.org/data/screenshots/aftermath/tlc/tlc_win_en_1_1_full.png
=> Groovie 2 announcement

composer.json, composer.lock
All versions must be PHP 7.3.x or 7.4.x compatible.
=> WEB: Upgrading dependencies

include/OrmObjects/Compatibility.php, schema.xml
Because it's Markdown, we can add whatever we need to in whatever format we need to.
=> WEB: Adding additional store links

include/OrmObjects/Compatibility.php
=> WEB: Adding note about data files to wiki link

data/en/credits.yaml
Companion PR to (now merged) scummvm/scummvm#3766.
=> CREDITS: Adding myself as the Webassembly maintainer

data/en/links.yaml
Since it's a mod of sorts, even if you have to provide the replacement tracks yourself.
I don't know how to build the web site, so this is completely untested. I hope I got the syntax right. Also, feel free to rewrite the text in any way you see fit.
=> WEB: Add link to instructions for replacing the music in Loom

templates/pages/screenshots_category.tpl
=> WEB: Adding screenshot head icon to gallery

data/en/news/20230124.markdown
This blog post announces new Director games for testing.
=> NEWS: new director games

include/Constants.php, include/OrmObjects/Compatibility.php, schema.xml
=> WEB: Adding ZOOM Platform link to Compatibility pages

data/en/news/20250319.markdown
Adding as PR for a final proof.
@mduggan If you have some time, please provide 3 or 4 screenshots of the games we can use for the announcements on our social media accounts and Discord in the comments.
If I have your final "go", I'll merge this and publish it on the website.
Thank you for your work on this!
=> WEB: Announce testing for Willy Beamish and Heart of China

data/en/news/20250516.markdown
Adding as a PR for a final proofreading.
I've provided some screenshots below, trying to avoid any spoilers.
@fracturehill Please proofread :) Thanks again for your hard work on these!
@sev-, @lotharsm, please help to publish this on our website and social media accounts
=> WEB: Announce testing for Nancy Drew 6 and 7
