data/news/de/20160119.xml
This is small fix for a broken HTML tag and a small typo in the German announcement of the "New Home".
=> WEB: Fix HTML tag in German announcement of the new server

include/Controller.php, index.php
As mentioned in f3c2203e2fc179e3f384e0499c34dcff63e792c1,
the language switching was always 1 behind. As in, the
language would be the last language you selected.
The first problem is that some of the smarty config variables
were being set after the call to _smarty->config_load(). Since
the smarty instance is cached, it was using the last set of variables.
I don't know why the production web site isn't throwing errors. My
personal set up wouldn't load until I could set _smarty->compile_dir
the first time. Perhaps the language update was done on the fly, so
smarty was still cached.
The next potential problem is persistence with $_SESSION.
The session is never initialized with session_start(). However,
the production php.ini may have session auto start enabled.
=> WEB: Fix language switching

data/news/de/20150330.xml, data/news/de/20150913.xml, data/news/de/20151111.xml, data/news/de/20151122.xml, data/news/de/20151206.xml, data/news/de/20160119.xml, lang/lang.de.ini
This pull request converts the existing German website from the currently very informal "du" form of address to the more polite and formal "Sie" form of address as suggested by @SimSaw.
I converted the entire website except the downloads.de.xml file which seems to be obsolete as soon as the next version of ScummVM is released. 
Maybe someone can merge the downloads.xml file in the lang.ini? :)
=> WEB: Convert the German website to a more polite form of address

data/news/de/20160201.xml
This commit fixes a few typos and grammar mistakes in the German 1.8.0 testing announcement.
Sorry for that.
=> WEB: Fix typos + grammar in German 1.8.0 testing announcement

data/news/de/20151206.xml, data/news/de/20160201.xml
BS2.5 and 1.8.0 testing announcements now use the German release titles instead of the English ones.
=> WEB: Use German release titles in news

data/news/de/20160304.xml
This time using proper UTF-8 encoding.
Sorry, I don't get why my editor switched to ANSI without asking me.
=> WEB/DE: Fix encoding in 1.8.0 announcement

include/config.inc.php
According to the Debian website for the ScummVM package [https://packages.debian.org/sid/scummvm], the current version available in the "sid" repository is 1.7.0 and not 1.6.0 as stated on the ScummVM downloads website.
=> WEB: Update RELEASE_DEBIAN to 1.7.0

css/lang-menu.css, css/layout.css, templates/lang_menu.tpl
1. Fixed #52 by using a larger `min-width` for the page.
My earlier change made it disappear, but even before that, the language button was hovering over the logo.
2. The button was unusable on mobile. Since mobile doesn't have "hover", you have to click on it. Clicking on it reloaded the main page since it was a `<a href="">`. I fixed this by changing the `<a>` to a `<span>` and prettied it up by changing the cursor to a pointer. I also took the opportunity to remove some unused CSS, and vertically center the "language book" image in the tab.
=> Move language button to top of screen, mobile fixes

.htaccess
The default is to have a session cookie, but it might be better to remember the selected language for longer than just the current session. This commit is here for discussion as I don't know if this is what we want. Also I picked 60 days randomly. Maybe we want more, maybe less.
=> WEB: Set language cookie to expire after 60 days

data/menus.de.xml, data/menus.fr.xml, data/menus.it.xml, data/menus.ru.xml, data/menus.xml
Now that we moved everything (downloads, ticket system, mailing lists...) away from sf.net, I think it makes sense to remove the last remaining links to the sf.net project home.
=> WEB: Remove links to sf.net project home

css/lang-menu.css
Simply centered button.
This solution uses `transform` property, which is CSS3, but should be supported quite well. There are browser-specific prefix-versions of this property, which are supported by older versions of browsers, but probably still not all of them.
It looks like that: ![Centered button](http://tkachov.ru/images/wyN7hwrYWs0ttMQ7KtQKOdjC7fRk0UlxT94A5xkc/step2.png)
@salty-horse says he assumed it's supposed to be centered between the logo and the characters instead of the whole page.
=> WEB: Center "Language" button

data/menus.de.xml, data/menus.fr.xml, data/menus.it.xml, data/menus.ru.xml, data/menus.xml
The menus still linked to the old feature/bug tracker on sourceforge.
=> WEB: Remove links to the old Feature Tracker

data/screenshots.xml
Rama was listed in the other section, but it should be in SCI.
=> WEB: Move RAMA screenshots reference to SCI

lang/lang.ini, scss/components/_cookie.scss, scss/main.scss, templates/components/cookie.tpl, templates/pages/index.tpl
To comply with EU regulations, we must ask customers if they're willing to let us use tracking cookies. This PR adds a floating form on the bottom that requires the user to consent to in order to enable google analytics.  
There doesn't seem to be a way to use GA without it storing a cookie, so if the user doesn't provide consent, the script never even loads.
This addresses #89
=> Add a cookie consent form for Google Analytics

lang/i18n/lang.en.json
Since current versions of ScummVM are not only available in Debian sid, but also in many more bleeding edge Linux distributions like Arch, Manjaro, Fedora, openSUSE Tumbleweed, current Ubuntu and many more, I propose to remove the reference to Debian sid on the download page and use a more generic wording instead:
"ScummVM {release} is also available in the software repositories of many GNU/Linux distributions."
Please let me hear your thoughts.
=> WEB: Remove the reference to Debian unstable; use generic wording instead

data/links.xml
* Removing dead links to official and unofficial ports
* All are dead except the GP32 port, which hasn't been updated in 6 years
* Changing hqx link to Wikipedia, since the main site is dead
* Correcting link to Ogg Vorbis
=> DATA: Fixing/removing broken links

README.md
Thanks to the help of @SupSuper, @lotharsm, and @criezy on Discord, I was able to figure out how to get past an issue I was having with YAML pages like `/credits` not showing up correctly. I've added instructions to README.md so that others can avoid the same issues.
Includes a description of why the Apple-supplied version of PHP won't work, which is an issue that I ran into.
=> DOC: Adding prerequisite to install PHP and PECL

include/Models/ArticleModel.php, include/Models/CompatibilityModel.php, include/Models/CreditsModel.php, include/Models/DocumentationModel.php, include/Models/DownloadsModel.php, include/Models/FAQModel.php, include/Models/GameDemosModel.php, include/Models/GamesModel.php, include/Models/LinksModel.php, include/Models/MenuModel.php, include/Models/ScreenshotsModel.php, include/Models/SubprojectsModel.php
Fixes the following [Codacy issues](https://app.codacy.com/manual/sev-/scummvm-web/issues):
* Avoid variables with short names like `$a`. Configured minimum length is 3.
* Avoid unused local variables such as '$key'.
=> BUILD: Standardizing the variable names for parsing data

data/links.yaml
This updates all the URLs in the Links page to the latest versions / HTTPS.
Some other things I noticed:
- The links in "Technical information about SCUMM" are gone, should we remove this section?
- Should we remove the Ultima engine links now that they've merged with ScummVM?
=> WEB: Update URLs in Links page

data/en/links.yaml
This updates the defunct links in the Technical Information section:
- SCUMM Hacking directs to the archive now hosted by MixNMojo.
- AGI Development directs to the wiki now hosted by SierraHelp.
=> WEB: Update broken Technical links

scss/theme/_themes.scss
This makes hyperlinks consistent with other pages, including ones with lots of links such as the Downloads page
The concern was raised in Discord that there was too much red now on the tables. For comparison, we already have a similar amount of red on the downloads page, so this change is consistent with the rest of the site.
Since the amount of red on that page is considered acceptable, I do not think that this is too much here either, and it helps with website consistency. Plus, red hyperlinks means the clickable words can now be easily distinguished from the unclickable words.
=> Changing table hyperlinks from black to default color

data/en/scummvm_downloads.yaml
The old website no longer exists. See https://www.videoproc.com/resource/what-happened-to-audiocoding.htm
=> WEB: Updating link to FAAD2

public_html/index.php
Fixing an issue that prevented loading the compatibility page for games with hyphens in their short name, such as `private-eye` and `agi-fanmade`. Previously, attempting to go to the link for such a page would result in redirecting to the index page. Now the page is properly loaded.
=> WEB: Fixing issue redirecting games with hyphens

include/OrmObjects/Compatibility.php, schema.xml
Add a new field to the game table called `wikipedia_page`, which is the URL page title for the game's corresponding page on English Wikipedia.
The field has been filed out for a few games (such as *Martian Memorandum* and *Manhunter: New York*), but more will need to be filled out.
=> WEB: Add a Wikipedia link for games

data/en/strings.json
The URL goes to [a section](https://www.scummvm.org/downloads/#daily) that has "Daily Builds" as its header, so the link name should be consistent.
=> WEB: Changing "Daily Snapshots" link to "Daily Builds"

data/en/links.yaml
All the Ultima engines have been merged with ScummVM. That leaves DOSBox, which has a description that says "DOSBox does not really quite fit in here", which means it's not really worth keeping.
=> DATA: Removing other game engines from links

data/en/strings.json, include/Objects/File.php, scss/pages/_downloads.scss, templates/components/list_items.tpl
It appears that at one point the data spreadsheet included a `type` field. This is no longer the case and so all of this is not used, providing unnecessary confusion and maintenance.
=> WEB: Removing file.getType() and related dead code

include/Constants.php, include/DataUtils.php, include/Models/DownloadsModel.php, include/Objects/File.php, include/OrmObjects/Download.php, schema.xml
In order to simplify the process of updating version downloads, [downloads spreadsheet table](https://docs.google.com/spreadsheets/d/1QzwFleEKXOsE59cYMOcQB7C2f0Np48uAQOCG8kicX_s/edit#gid=1057392663) now includes a `version` column and the `url` field is much simpler. In order to update a new version, simply change the value in the `version` field.
Further improvements can be made, but for now this is an improvement that keeps parity with the previous code.
----
When this code gets merged, the following steps should be taken on the spreadsheet:
1. Delete the old `scummvm_downloads` table
2. Rename `Thunderforge_wip_scummvm_downloads` to `scummvm_downloads`
Because the code references sheet ids and not tab names, no further action needs to be taken.
=> DATA: Changing downloads table to use version column

include/OrmObjects/Download.php
Makes this appear properly
```
IRIX (6.5.{$version}, n32, mips3) package
IRIX (6.5.{$version}, n32, mips4) package
```
=> WEB: Replacing {$version} in file name

data/de/strings.json, data/el/strings.json, data/en/menus.yaml, data/en/strings.json, data/es/strings.json, data/fi/strings.json, data/fr/strings.json, data/he/strings.json, data/it/strings.json, data/pl/strings.json, data/pt-BR/strings.json, data/pt-PT/strings.json, data/ru/strings.json
"Patch Tracker" was a term that once made sense, but since we moved to GitHub, it no longer means anything. Changing to the GitHub terminology of "Pull Requests".
This will unfortunately require a re-translation in all localizations.
=> WEB: Renaming "Patch Tracker" to "Pull Requests"

include/Models/DownloadsModel.php
If there is no recommended download for the given agent, the page now loads as expected. Tested with user agent
```
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.4) Gecko/20100625 Gentoo Firefox/3.6.4
```
=> WEB: Fixing when there is no download link for the user agent

include/Models/DownloadsModel.php
If the download button appears and links to an external URL, it now properly generates the  URL
Tested on with user agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
```
The link is https://downloads.scummvm.org/frs/scummvm/2.5.0/https://snapcraft.io/scummvm
The link is https://snapcraft.io/scummvm
=> WEB: Fixing when the recommended download link is an external URL

include/Objects/DownloadsSection.php
Previously, downloads always got added to the end of the list. Now, the download is added to the end and then the list is sorted by version, meaning that the download will be moved to be the last one of all the downloads with that version.
Version 0.11.1 was at the bottom of the list.
Version 0.11.1 is now properly after 1.0.0, but before 0.9.1.
=> WEB: Sorting downloads by version after a new one is inserted

data/en/menus.yaml, data/en/strings.json
There are several translation projects aside from the ScummVM, such as the website and several game translations. Instead of linking to only the ScummVM project, now I link to the overall project that shows them all.
A two-line hyperlink labeled "Translate ScummVM" goes to https://translations.scummvm.org/projects/scummvm/scummvm/
A one-line hyperlink labeled "Translations" goes to https://translations.scummvm.org/projects/
=> I10N: Changing translations link to general project page

include/Constants.php, include/Objects/File.php
No extra file information appears after hyperlinks.
Several pieces of file information appear after hyperlinks. Clicking on `sha256` results in the file hash appearing.
=> WEB: Fixing extra info not appearing for ScummVM download links

include/Models/DownloadsModel.php
fix wrong url for macos. download did not work because link is like this:
https://downloads.scummvm.orgfrs/scummvm/2.5.1/scummvm-2.5.1-macosx.dmg
=> Missing slash between DOWNLOADS_BASE and DOWNLOADS_URL

include/Models/DownloadsModel.php, templates/components/list_items.tpl
Now that we have .exe files for 64-bit Windows, it's no longer accurate to say `Win32 .exe`. This was also unique behavior for Windows; we did not indicate bitness in this way for any other operating system.
=> WEB: Removing Win32 label in extra info

templates/components/recommended_download.tpl
The recommended download section includes the version, OS, and description, with each separated by a bullet (•). Before, the bullet following the OS would always appear, even if there was no description after it. Now the bullet will only appear if there is a description.
=> WEB: Remove trailing bullet if recommended download lacks a description

templates/components/recommended_download.tpl
The button now reads "Download ScummVM 2.5.1" instead of "Download ScummVM" and the next line beginning with "Version 2.5.1".
This also has an advantage of reducing the number of words that need to be translated into foreign languages.
=> WEB: Moving location of recommended download version

data/en/strings.json, templates/components/recommended_download.tpl
A new string, `downloadsBadgeTitle`, will need to be translated through Weblate.
=> I10N: Making Recommended Download button title text translatable

include/FileUtils.php
We don't need second precision when showing last updated, so reducing from datetime to date. Changing to ISO 8601 has the added benefit of reducing visual complexity and also preventing the need to translate the spelled out dates.
=> WEB: Changing getLastModified($path) to return as ISO 8601 date

templates/components/list_items.tpl
Removing extra spaces and adding a comma
=> WEB: Fixing sha256 formatting

include/OrmObjects/Screenshot.php
`Spy Fox in "Dry Cereal"` was appearing as `Spy Fox in`. Replacing the quotes with `&quot;` so it renders properly in HTML.
=> WEB: Fixing captions for games with quotes in name

include/Constants.php, include/Objects/File.php
I have proposed moving daily downloads of ScummVM and ScummVM Tools from `frs/daily/` to `frs/scummvm/daily/` and `frs/scummvm-tools/daily` respectively. This PR contains simplifications to the code that would result from this. 
The download links can be found at https://www.scummvm.org/downloads/#daily
* https://downloads.scummvm.org/frs/daily/scummvm-snapshot-win32.exe
* https://downloads.scummvm.org/frs/daily/scummvm-tools-snapshot-win32.zip
* https://downloads.scummvm.org/frs/scummvm/daily/scummvm-snapshot-win32.exe
* https://downloads.scummvm.org/frs/scummvm-tools/daily/scummvm-tools-snapshot-win32.zip
=> WEB: Moving daily download file path

include/Constants.php, include/Models/DownloadsModel.php
Now that we have the "version" column on the spreadsheet, the constants are unnecessary. This was a holdover from back when versions were determined by the file names and these URLs didn't have them.
=> DATA: Removing constants for Android & Ubuntu versions

data/en/links.yaml
The code expects "notes", but the data was stored as "descriptions". Changing to "notes".
=> DATA: Restoring notes for links

include/Objects/File.php, include/OrmObjects/Download.php
Fixes errors such as
```
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/Will/OpenSource/scummvm-web/include/Objects/File.php on line 26
```
=> WEB: Adding null check before string replacement

include/Models/ScreenshotsModel.php
Fixes [#13340](https://bugs.scummvm.org/ticket/13340).
When getting a count of the number of screenshots for a game or series, only count the full screenshots. This prevents doubling the count because both the small and large versions are included.
=> IMAGES: Only count full screenshots

include/OrmObjects/Screenshot.php
Fixes an issue where the caption of `King's Quest I: Quest for the Crown (2.0F 1987-05-05 5.25"/3.5"/DOS/English)` was truncated to `King's Quest I: Quest for the Crown (2.0F 1987-05-05 5.25`.
Replaces #215.
=> WEB: Escaping special characters in the entire caption

include/OrmObjects/Screenshot.php, include/OrmObjects/ScreenshotQuery.php, schema.xml
This is an attempt at fixing the [regression](https://bugs.scummvm.org/ticket/13328) introduced by PR #207 .
The "filemask" column was removed, so now every game screenshot is (incorrectly) duplicated for each variant. This tries to automatically determine the filemask based on the screenshot column data instead. The format is `<game>_<platform>_<language>_<variant>_*`
=> WEB: Automatically determine filemask for screenshots

data/en/menus.yaml, data/en/strings.json
"Games" could refer to either 
* Games that are freeware
* Games supported by ScummVM (i.e. Compatibility)
Changing to "Freeware Games" to avoid this ambiguity.
=> WEB: Changing menu link from "Games" to "Freeware Games"

scss/components/_card.scss, scss/pages/_screenshots.scss, templates/pages/screenshots_category.tpl
Improvements are:
* Long captions are now always visible instead of being cut off
* Differently sized cards no longer cause gaps
* Images are now always at a visible size instead of becoming too small to see
There are no gaps, images stay a consistently readable size, and captions are always shown in full. 
Images are centered on the page, preventing the possibility of a wide gap on the right side
=> WEB: Changing grid view to be more responsive

scss/components/_card.scss, templates/pages/screenshots_category.tpl
It's still preserved for the monkey at the bottom of the menu.
=> IMAGES: Removing pixelated rendering class for thumbnails

include/OrmObjects/Screenshot.php, scss/pages/_screenshots.scss, templates/components/random_screenshot.tpl
The caption is a hyperlink that goes to the corresponding game page on https://www.scummvm.org/compatibility/ . This allows users to quickly look up compatibility info as well as see which platforms are supported.
=> WEB: Adding a caption to random screenshots

include/Constants.php, include/OrmObjects/Compatibility.php, schema.xml
This provides GOG.com and Steam links. In the future, we can expand this to additional websites, including free downloads from the developer sites.
=> WEB: Adding "Available At" info to game compatibility pages

scss/base/_base.scss
For some reason the menu banners are vertically stretched. I assume it's some obsolete formatting, as there's no point in forcing an image size via CSS, so I removed that rule.
Before:
After:
=> WEB: Don't stretch menu banners

scss/pages/_compatibility.scss, templates/pages/compatibility.tpl
This seems to have been for some planned functionality to highlight recent changes, but it was never completed. Since it is unused, remove it.
=> WEB: Removing "Updated" level from Compatibility legend

data/en/news/20220524.markdown
There were several typos and odd phrases in the original. Fixing it.
=> NEWS: Fixing typos and odd phrasing in Chewy announcement

templates/pages/compatibility.tpl
Hovering over the compatibility ratings will now show a tooltip with the compatibility rating's description.
=> WEB: Adding tooltips to compatibility ratings

include/FileUtils.php
This is a result of the discussion from PR #230 where the consensus was that the consistent and accurate, if inconvenient, units (KiB, MiB, GiB) were preferred over the ambiguous units (kB, MB, GB).
=> WEB: Displaying file sizes as MiB etc

data/en/links.yaml
Adds a link to [the remastered soundtracks of The Fat Man](https://thefatmanandteamfat.bandcamp.com).
=> WEB: Adding link to The Fat Man remastered soundtracks

dumper-companion/src/Dumper.tsx
I was working with a `.cdr` file today, and realized that several Mac-specific file extensions were missing.
=> Dumper companion: more Mac extensions

data/en/links.yaml
These scalers, and many more, are already [documented in the ScummVM docs](https://docs.scummvm.org/en/latest/advanced_topics/understand_graphics.html?highlight=sdl#a-comparison-of-sdl-surface-software-scalers), so it's redundant to have them here (and without the other scalers). Plus one of the websites isn't live any more and only linked via Wayback Machine.
=> WEB: Removing links to scalers

data/en/strings.json, include/OrmObjects/Compatibility.php, scss/pages/_compatibility.scss, templates/components/compatibility_details.tpl, templates/pages/compatibility.tpl
This replaces "Game Short Name". When a version newer than 2.2.0 is displayed, the id will be in the format of `engine_id:game_id`. If version 2.2.0 or later is displayed, the id will be in the format of `game_id`.
=> WEB: Adding "ScummVM ID" to compatibility page

data/en/compatibility.yaml, include/DataUtils.php, include/OrmObjects/Compatibility.php, include/OrmObjects/Screenshot.php, schema.xml, templates/pages/compatibility.tpl
This change only affects the [compatibility page](https://www.scummvm.org/compatibility/DEV/). Future PRs will address other aspects of the website.
Previously we could have a name collision, as with `qfq1`. Now we can have more unique names: `agi:qfq1` and `sci:qfg1`. This matches the "ScummVM ID" currently visible on the compatibility page.
Note that this PR does change the compatibility URLs:
* **Before:** https://www.scummvm.org/compatibility/DEV/astrochicken/
* **After:** https://www.scummvm.org/compatibility/DEV/sci:astrochicken/
=> WEB: Changing Compatibility ids to engine_id:game_id

dumper-companion/src/Dumper.tsx, dumper-companion/src/hfs/directory.ts
Adds "Always use MacBinary encoding" option, which always dumps files as MacBinary even if they have no resource fork, to keep the HFS type/creator codes intact.
=> DUMPER: Add "Always use MacBinary encoding" option.

data/en/press_articles.yaml
Since I can't get a direct link to the article, I figure linking to the magazine landing page is the best way to do it.
=> WEB: Adding Wireframe press article

data/en/compatibility.yaml, data/en/director_demos.yaml, data/en/game_demos.yaml, data/en/game_downloads.yaml, data/en/games.yaml, data/en/screenshots.yaml, include/DataUtils.php, include/Models/ScreenshotsModel.php, include/OrmObjects/Compatibility.php, include/OrmObjects/Screenshot.php, templates/components/list_items.tpl
Previously, game ids were displayed in the form of `monkey`. Now they are displayed in the form of `scumm:monkey`.
Note that this changes some of the URLs for the screenshots and compatibility pages.
* https://www.scummvm.org/compatibility/DEV/monkey/
* https://www.scummvm.org/compatibility/DEV/scumm:monkey/
=> WEB: Using full game id across the site

include/OrmObjects/Compatibility.php, templates/components/compatibility_details.tpl
Fixes [issue #13720](https://bugs.scummvm.org/ticket/13720).
The old system used a placeholder and was overbroad in its regex replace for that placeholder, which garbled links. Since we don't need a special regex for a placeholder, this does the job in a simpler and more reliable way.
=> WEB: Using simple replace for support description

data/en/links.yaml
I figure we should advertise ScummVM-related stuff over third-party stuff.
=> WEB: Moving game mods to top of links page

LICENSE
The license was not explicitly declared in the repo. It matches the one [used for ScummVM](https://github.com/scummvm/scummvm/blob/master/COPYING).
=> Create LICENSE file with GPLv3

dumper-companion/src/Dumper.tsx
This is used by some software for DiskCopy images. The [Applesauce software](https://applesaucefdc.com/software/) uses this for Mac disk images, for example.
=> DUMPER: add dc42 extension
